numbers=[5,2,1,5,5,5,7,4]
numbers.append(20)
print(numbers)
numbers.insert(2,10)
print(numbers)
numbers.remove(1)
print(numbers)
numbers.pop()
print(numbers)
print(numbers.index(5))
print(50 in numbers)
print(numbers.count(5))
numbers.remove(5)
print("----->",numbers)
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
num2= numbers.copy()
print(num2)
numbers.clear()
print(numbers)