import numpy as np
a = np.array([10, 20, 30, 40, 50])
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))
print(np.var(a))
print(np.median(a))
print(np.percentile(a, 25))
print(np.percentile(a, 50))
print(np.percentile(a, 75))